### ISSUE TITLE
broken cluster overview page on invalid datacenter name

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#1124]
The problem happens, when the name of a datacenter in the `datacenter.yaml` get changed. In this example `openstack-region1`. The cluster was created before. So the cluster get the error
```
  Error Message:  invalid datacenter "openstack-region1"
  Error Reason:   ReconcileError
```
* The original error get not displayed
* The health check is no displayed
Error on the browser console:
```
ERROR TypeError: Cannot read property 'spec' of null
    at e._next (9.43627f69459bd3269a3d.js:1)
    at e.__tryOrUnsub (main.e89dcd06edb28554d14f.js:1)
    at e.next (main.e89dcd06edb28554d14f.js:1)
    at e._next (main.e89dcd06edb28554d14f.js:1)
    at e.next (main.e89dcd06edb28554d14f.js:1)
    at e._next (main.e89dcd06edb28554d14f.js:1)
    at e.next (main.e89dcd06edb28554d14f.js:1)
    at e._next (main.e89dcd06edb28554d14f.js:1)
    at e.next (main.e89dcd06edb28554d14f.js:1)
    at e._subscribe (main.e89dcd06edb28554d14f.js:1)
```
Maybe there is just a missing null check somewhere. What checks the mapping between cluster datacenter value and configured datacenter value.
![image (1)](https://user-images.githubusercontent.com/4659261/54284802-e88ab880-45a0-11e9-85f9-90c265a37efb.png)

- - -
You can reproduce it like follow:
1. create a cluster
2. rename a datacenter name e.g. `openstack-region1` -> `xxxx`:
```
#==================================
#============OpenStack=============
#==================================
  openstack-region1:
    location: Berlin
    seed: europe-west3-c
```
3. helm upgrade ...
