### ISSUE TITLE
[bug] incorrect VM template during cluster creation on Vsphere

### ISSUE THREAD

**Issue by zreigz** [kubermatic/dashboard#1344]
**Steps to reproduce:**
Create a cluster on Vsphere. Use the Ubuntu operating system.

Dashboard generates structure to call the endpoint with incorrect `nodeDeployment` value for OS template:
```
"nodeDeployment":{"spec":{"template":{"cloud":{"vsphere":{"cpus":1,"memory":512,"template":"ubuntu-template","diskSizeGB":null}}
```
The template is set for `ubuntu-template` but datacenter configuration for Vsphere and this datacenter specifies different one: 
```
        templates:
          ubuntu: "machine-controller-e2e-ubuntu"
          centos: "machine-controller-e2e-centos"
          coreos: "machine-controller-e2e-coreos"
```

I've noticed the data center endpoint is never called to retrieve the correct template: `/api/v1/dc/{dc}` like `/api/v1/dc/vsphere-hamburg` in this case

This bug can potentially exist for other providers.
