### ISSUE TITLE
Allow help text for Addon Form Fields

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2728]
**What is the problem, where is it and why is it an issue?**
Currently, as far as our documentation is concerned, we can extend Addons with new Form Fields, like so:

```yaml
  formSpec:
    - displayName: Port
      internalName: port
      required: false
      type: number
```

This yields

![screenshot-2020-10-23-132730](https://user-images.githubusercontent.com/127499/96999475-7c6e8580-1535-11eb-812a-892d1c46ebed.png)

Unfortunately, there is no way yet to provide any context for the form fields. Likewise, there is no documentation on what `type`s we support.

**Suggest how to fix it, if possible**
- Add a new `description` or `helpText` field to each form control.
- Display this new help text right below the form element (or next to it).
- Document on docs.kubermatic.com what form field types are available.
