### ISSUE TITLE
UI: vSphere VM template not filled if only one OS templage is specified

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#3207]
**What happened?**:
If at the seed configuration is only one OS template image is specified, the UI doesn't show up the image template value
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/939cb271-a626-4be2-ad82-43aa05a7ce52)

`seed.yaml`:
```
apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  name: tobi-seed-run-2
  namespace: kubermatic
spec:
  # Optional: Country of the seed as ISO-3166 two-letter code, e.g. DE or UK.
  # For informational purposes in the Kubermatic dashboard only.
  country: DE
  # Datacenters contains a map of the possible datacenters (DCs) in this seed.
  # Each DC must have a globally unique identifier (i.e. names must be unique
  # across all seeds).
  datacenters:
########### Vsphere
    tobi-run-2-vsphere:
      # Optional: Country of the seed as ISO-3166 two-letter code, e.g. DE or UK.
      # For informational purposes in the Kubermatic dashboard only.
      country: DE
      location: Hamburg (onsite-seed)
      spec:
        vsphere:
          allow_insecure: false
          cluster: cl-1
          datacenter: dc-1
          datastore: exsi-nas
          endpoint: https://vcenter.loodse.io
          root_path: /dc-1/vm/kubermatic
          templates:
            flatcar: flatcar_2021-02.ova
```

**What should happen?**:
`flatcar_2021-02.ova` should be filled out

**How to reproduce?**:
Create/Configure a vSphere seed datacenter with only one OS template specified, like in the above example + create a user cluster on this seed.

**Environment**
- UI Version: `weekly-2021-12`
- API Version: `weekly-2021-12`
- Domain: `run-2`
- Others:
