### ISSUE TITLE
Disallow disabling Konnectivity for Cilium+ebpf

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/dashboard#4533]
**What would you like to be added? / User Story**:
On the "Edit Cluster" page, there is an option to enable/disable Konnectivity:

![image](https://user-images.githubusercontent.com/15926980/171883919-de201527-5af9-4de4-a9d6-fe5376db04cc.png)

However, if the cluster uses Cilium CNI with ebpf proxy mode, such as:
```
spec:
  clusterNetwork:
    proxyMode: ebpf
  cniPlugin:
    type: cilium
    version: v1.11
```

It is not possible to disable Konnectivity, as that would result into the following error:
```
invalid cluster: spec.networkConfig.proxyMode: Invalid value: "ebpf": ebpf proxy mode can be used only when Konnectivity is enabled
```

Therefore for this particular CNI / proxy mode combination, it should not be allowed to disable Konenctivity.
