### ISSUE TITLE
KubeVirt UI Improvements

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4793]
### Adjust Logo + Mark as Tech Preview
Adding Technology Preview to Logo

### Rename & Adjust
* Cluster settings page:
   * Title "Pre-Allocated Data Volume" to "Custom Local Disks"
   * Button "Add Data Volume" to "Add Local Disk"
   * Description "No pre-allocated data volumes configured. Use the add button above to configure" to "Custom local disks are optional disks used for the provisioning of nodes with custom images. [Learn more >](https://docs.kubermatic.com/kubermatic/v2.20/architecture/support_policy/provider_support_matrix/kubevirt/kubevirt/)" (this link will probably be adjusted after the documentation update) 
   * "URL" to "Operating System URL" (visible after adding a data volume)
   * "Volume N" to "Disk N" (indexer of volumes)
* Initial Nodes page:
    * Primary disk hint "Use URL or namespace/PVC name format" to "Use URL or Custom Local Disk name"
    * Title "Affinity Settings" to "Scheduling Settings"

### Add Hints/Descriptions
* Initial Nodes page:
    * Secondary disks description empty state: "Optional disks that will be mounted to the nodes. Configure up to three disks."
    * Pod Affinity Preset - "Ensures two tenant nodes to be co-located in a single infrastructure node. Hard and soft values represent required and prefered scheduling."
    * Pod Anit-Affinity Preset - "Allows you to prevent tenant nodes to be co-located in a single infrastructure node. Hard and soft values represent required and prefered scheduling."
    * Nodes Affinity - "Ensures that tenant nodes are hosted on particular nodes."

### Advanced Settings
- Move Scheduling Settings (previously called Affinity Settings) into an "Advanced Scheduling Settings" section. Functionality mirrors "advanced network settings" on the "2) cluster" step.
 ![image.png](https://images.zenhubusercontent.com/5dc5412ea240680001cc35aa/4d40c0dc-f570-4978-b67b-971a4ee31ff5)
- Move Custom Local Disks (Previously pre-allocated data volumes) into an "Advanced Disk Configuration" section same as with Scheduling Settings above

### Make Custom Local Disk Information More Accessible
We need to make the information able to be viewed by the user on
- the create summary page
- the cluster details page 

(design shows preset but see Waseems comment below) 
![image](https://user-images.githubusercontent.com/49145827/184123622-5eb96193-930b-4e28-9bc0-d8a179b58c23.png)

![image](https://user-images.githubusercontent.com/49145827/184124216-a7d9d0aa-f599-42a0-baca-77b993164a79.png)

**Comment by cschieder** [comment]
Copy of kubermatic/kubermatic#10701, closing the copy to avoid duplicates

**Comment by Waseem826** [comment]
#### Cluster Summary Page:

![screenshot-localhost_8000-2022 08 10-13_34_28](https://user-images.githubusercontent.com/13975988/183856212-0bb397a4-da63-46ae-acfe-f397e763482c.png)

All of these newly added settings are displayed on cluster summary page. However, pre-allocated data volume settings are only displayed when non-preset option is selected on 3rd step. This behavior is same for all other providers as well so if preset is selected then only selected preset is displayed on summary page.

#### Cluster Details Page:
Affinity settings are not displayed on cluster details page but instead those are displayed on machine deployment details page along with other settings which are configured on 4th step.

![screenshot-localhost_8000-2022 08 10-13_39_21](https://user-images.githubusercontent.com/13975988/183857068-e5f88815-f2b1-4dca-b40a-4e87e0459911.png)

Regarding pre-allocated data volume settings: I'm not sure if we can display them on cluster details page because we don't get that information after cluster has been created.

**Comment by mfranczy** [comment]
@sankalp-r can you check this?
> Regarding pre-allocated data volume settings: I'm not sure if we can display them on cluster details page because we don't get that information after cluster has been created.

**Comment by mfranczy** [comment]
@Waseem826 my apologies we missed the endpoint to list pre-allocated-data-volumes, @sankalp-r will prepare the endpoint for you soon.

**Comment by mfranczy** [comment]
@Waseem826 we have this info under the cluster object. Do you have any endpoint to get cluster details?

```
spec:                                                                                                                                                                                                                                         
  auditLogging: {}                                                                                                                                                                                                                              cloud:                                                                                                                                                                                                                                      
    dc: kubevirt-eu-central-1a                                                                                                                                                                                                                
    kubevirt:                                                                                                                                                                                                                                                                                                                                                                                                                                              
      preAllocatedDataVolumes:                                                                                                                                                                                                                
      - name: centos-test                                                                                                                                                                                                                     
        size: 10Gi                                                                                                                                                                                                                            
        storageClass: standard                                                                                                                                                                                                                
        url: http://image-registry.default.svc.cluster.local/centos.im
```
