### ISSUE TITLE
VSphere Node Deployment is not configurable

### ISSUE THREAD

**Issue by soer3n** [kubermatic/dashboard#6165]
### What happened

At my current employer we are evaluating the Kubermatic Community Edition with vSphere as the main cloud provider.

Since version 2.22 we cannot edit ram, cpu and disk size for machine deployments. As far as i found out the previously configured setting is displayed correctly in step 3 of the wizard for configuring the initial machine deployment  but in the summary always 2 cpus, 4 gb ram and 10 gb disk size are displayed. Even if i go back from the summary step to the inital machine deployment we can see the previously configured setting but not in the summary. We also tested it with another vCenter in our infrastructure and version 2.23 with the same result. We also tested ubuntu and rockylinux as the selected distro.

It's also not possible for us to create machine deployments after the initial cluster creation via dashboard with the same error. An error is thrown due to the size of more than 10 gb of our base ova template.

Screenshot from Step 3:

<img width="437" alt="kkp_wizard_md" src="https://github.com/kubermatic/dashboard/assets/43064202/9f131e47-5bac-4982-a1b0-37cc51a8118e">

Screenshot from Summary Step:

<img width="453" alt="kkp_wizard_summary" src="https://github.com/kubermatic/dashboard/assets/43064202/9a4ca049-4268-44a8-9609-e9f5251e810d">

We are using neither any default cluster template nor any specific default component settings. In 2.21 everything works fine for us. We started the dashboard also locally with tags v2.21.9 and v.2.23.1 where we saw the same behaviour. For v2.21.9 it works, for v2.23.1 not.

### Expected behavior

Worker Nodes should be provisioned in vCenter with configured settings.

### How to reproduce

I wonder why no issue was reported until now but from my point of view we configured nothing special for our vcenter in the kubermatic resources. Actually it's just the configuration in our seed.yaml which looks like this:

```
...
      spec:
        vsphere:
          endpoint: "..."
          datacenter: "..."
          datastore: "..."
          cluster: "..."
          allowInsecure: true
          rootPath: "..."
          templates:
            ubuntu: "..."
            rockylinux: "..."

```

### Environment
- UI Version: 2.22, 2.23
- API Version: 2.22, 2.23
- Domain: n/a
- Others:

### Current workaround

We can only create clusters with cluster templates via dashboard.

**Comment by ahmedwaleedmalik** [comment]
@soer3n thanks for opening the issue, we'll look into this.

**Comment by ahmedwaleedmalik** [comment]
So, I've tried replicating this against the following environments and it's working fine:

- v2.23.1
- v2.22.5

**Comment by soer3n** [comment]
@ahmedwaleedmalik Yes, there was a default template with a few provider specific values. I created it last week when i was looking for the problem.
 
```
...
  spec:
    cloud:
       providerName: "vsphere"
       dc: "datacenter"
       vsphere:
           infraManagementUser: {}
           storagePolicy: "storage-policy"
```

I tried it with the one from the docs again and also tried it without any default template but still with the same result. What is actually happening between wizard node deployment step and summary? Do you have any idea what could causing this behaviour?
