### ISSUE TITLE
Append orgId parameter to Grafana UI link in dashboard

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#6167]
**What would you like to be added? / User Story**:

When MLA is enabled on a user cluster, the "Monitoring, Logging & Alerting" tab has a link to Grafana, labeled "Open Grafana UI". 

Since a user might be part of multiple KKP projects, they are part of multiple organisations in Grafana. Grafana will remember the last organisation that a user switched to, so clicking the link might take you to data for a different project. While you are authorized to see the data in that organisation too, the clear intention was to get data for the cluster from which you clicked the link.

As such, we should append `?orgId=<Grafana Org ID>` to the URL. The Grafana org ID can be extracted from the `Project` resource, as it's annotated:

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: Project
metadata:
  annotations:
    mla.k8c.io/organization: "158"
  name: 22cqbfnfkd
```

This information is likely not exposed through the dashboard API yet, so it might be necessary to add it to some project-related workload (or even the responses for a cluster?).
