### ISSUE TITLE
Dashboard always displays "Update Available" even when there is none

### ISSUE THREAD

**Issue by SamuAlfageme** [kubermatic/dashboard#6719]
### What happened

![Screenshot 2024-06-24 at 12 42 31](https://github.com/kubermatic/dashboard/assets/2644445/daba7fa4-444b-4bd9-9bf9-7a3b18ca0160)

### Expected behavior

When the UC is already on the highest available k8s version, no "Update Available" message should be displayed on the `Change Control Plane Version` modal. 

### How to reproduce

- Click on the "Control Plane" dropdown.
- AFAICS, "Upgrade Available" is always displayed.

### Environment

- UI Version: 2.25.5
- API Version: 2.23

Here is the relevant chunk of my `KubermaticConfiguration`:

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
    name: kubermatic
    namespace: kubermatic
spec:
[...]
    versions:
        default: v1.29.6
        versions:
            - v1.28.7
            - v1.28.8
            - v1.28.9
            - v1.28.10
            - v1.28.11
            - v1.29.2
            - v1.29.3
            - v1.29.4
            - v1.29.5
            - v1.29.6
        updates:
            - from: 1.28.*
              to: 1.28.*
            - from: 1.28.*
              to: 1.29.*
            - from: 1.29.*
              to: 1.29.*
[...]
```

**Note**: maybe the `Update Available` label makes reference to the fact that a downgrade could technically be performed (since updates from `1.29.*` to `1.29.*` are allowed), but the wording is a bit confusing.
